
package ejerlavavajillas;

public class EjerLavavajilla extends javax.swing.JFrame {

    Lavavajilla lavavajilla = new Lavavajilla();
    
    public EjerLavavajilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCerrarPuerta = new javax.swing.JButton();
        jButtonEncender = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonEnjuagado = new javax.swing.JButton();
        jButtonPrelavado = new javax.swing.JButton();
        jButtonLavado = new javax.swing.JButton();
        jButtonAclarado = new javax.swing.JButton();
        jButtonSecado = new javax.swing.JButton();
        jButtonAvanceAutomatico = new javax.swing.JButton();
        jLabelPuerta = new javax.swing.JLabel();
        jTextFieldTextoPuerta = new javax.swing.JTextField();
        jLabelEnergia = new javax.swing.JLabel();
        jTextFieldTextoEnergia = new javax.swing.JTextField();
        jLabelPrograma = new javax.swing.JLabel();
        jTextFieldTextoPrograma = new javax.swing.JTextField();
        jButtonAbrirPuerta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCerrarPuerta.setText("Cerrar Puerta");
        jButtonCerrarPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarPuertaActionPerformed(evt);
            }
        });

        jButtonEncender.setText("Encender");
        jButtonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncenderActionPerformed(evt);
            }
        });

        jButtonApagar.setText("Apagar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonEnjuagado.setFont(new java.awt.Font("Yu Gothic", 0, 10)); // NOI18N
        jButtonEnjuagado.setText("Enjuagado");
        jButtonEnjuagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnjuagadoActionPerformed(evt);
            }
        });

        jButtonPrelavado.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jButtonPrelavado.setText("Prelavado");
        jButtonPrelavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrelavadoActionPerformed(evt);
            }
        });

        jButtonLavado.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jButtonLavado.setText("Lavado");
        jButtonLavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLavadoActionPerformed(evt);
            }
        });

        jButtonAclarado.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jButtonAclarado.setText("Aclarado");
        jButtonAclarado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAclaradoActionPerformed(evt);
            }
        });

        jButtonSecado.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jButtonSecado.setText("Secado");
        jButtonSecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSecadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEnjuagado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrelavado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLavado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAclarado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSecado, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrelavado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLavado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAclarado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSecado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnjuagado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButtonAvanceAutomatico.setText("Avanzar estado automaticamente");
        jButtonAvanceAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvanceAutomaticoActionPerformed(evt);
            }
        });

        jLabelPuerta.setText("Puerta:");

        jTextFieldTextoPuerta.setEditable(false);

        jLabelEnergia.setText("Energía:");

        jTextFieldTextoEnergia.setEditable(false);

        jLabelPrograma.setText("Programa:");

        jTextFieldTextoPrograma.setEditable(false);

        jButtonAbrirPuerta.setText("Abrir Puerta");
        jButtonAbrirPuerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirPuertaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPuerta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTextoPuerta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAbrirPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCerrarPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEnergia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTextoEnergia)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAvanceAutomatico)
                        .addGap(48, 48, 48)
                        .addComponent(jLabelPrograma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTextoPrograma)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCerrarPuerta)
                    .addComponent(jButtonEncender)
                    .addComponent(jButtonApagar)
                    .addComponent(jButtonAbrirPuerta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPuerta)
                    .addComponent(jTextFieldTextoPuerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEnergia)
                    .addComponent(jTextFieldTextoEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAvanceAutomatico)
                    .addComponent(jLabelPrograma)
                    .addComponent(jTextFieldTextoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirPuertaActionPerformed
        lavavajilla.setAbierto(true);
        jTextFieldTextoPuerta.setText(lavavajilla.getAbierto());
    }//GEN-LAST:event_jButtonAbrirPuertaActionPerformed

    private void jButtonCerrarPuertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarPuertaActionPerformed
        lavavajilla.setAbierto(false);
        jTextFieldTextoPuerta.setText(lavavajilla.getAbierto());
    }//GEN-LAST:event_jButtonCerrarPuertaActionPerformed

    private void jButtonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncenderActionPerformed
        lavavajilla.setEncendido(true);
        jTextFieldTextoEnergia.setText(lavavajilla.getEncendido());
    }//GEN-LAST:event_jButtonEncenderActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        lavavajilla.setEncendido(false);
        jTextFieldTextoEnergia.setText(lavavajilla.getEncendido());
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonEnjuagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnjuagadoActionPerformed
       lavavajilla.setPrograma(0);
       jTextFieldTextoPrograma.setText(lavavajilla.getPrograma());
    }//GEN-LAST:event_jButtonEnjuagadoActionPerformed

    private void jButtonPrelavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrelavadoActionPerformed
       lavavajilla.setPrograma(1);
       jTextFieldTextoPrograma.setText(lavavajilla.getPrograma());        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrelavadoActionPerformed

    private void jButtonLavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLavadoActionPerformed
       lavavajilla.setPrograma(2);
       jTextFieldTextoPrograma.setText(lavavajilla.getPrograma());
    }//GEN-LAST:event_jButtonLavadoActionPerformed

    private void jButtonAclaradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAclaradoActionPerformed
       lavavajilla.setPrograma(3);
       jTextFieldTextoPrograma.setText(lavavajilla.getPrograma());
    }//GEN-LAST:event_jButtonAclaradoActionPerformed

    private void jButtonSecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSecadoActionPerformed
       lavavajilla.setPrograma(4);
       jTextFieldTextoPrograma.setText(lavavajilla.getPrograma());
    }//GEN-LAST:event_jButtonSecadoActionPerformed

    private void jButtonAvanceAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvanceAutomaticoActionPerformed
        lavavajilla.avanzarPrograma();
        jTextFieldTextoPrograma.setText(lavavajilla.getPrograma());
    }//GEN-LAST:event_jButtonAvanceAutomaticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjerLavavajilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjerLavavajilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjerLavavajilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjerLavavajilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjerLavavajilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirPuerta;
    private javax.swing.JButton jButtonAclarado;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonAvanceAutomatico;
    private javax.swing.JButton jButtonCerrarPuerta;
    private javax.swing.JButton jButtonEncender;
    private javax.swing.JButton jButtonEnjuagado;
    private javax.swing.JButton jButtonLavado;
    private javax.swing.JButton jButtonPrelavado;
    private javax.swing.JButton jButtonSecado;
    private javax.swing.JLabel jLabelEnergia;
    private javax.swing.JLabel jLabelPrograma;
    private javax.swing.JLabel jLabelPuerta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldTextoEnergia;
    private javax.swing.JTextField jTextFieldTextoPrograma;
    private javax.swing.JTextField jTextFieldTextoPuerta;
    // End of variables declaration//GEN-END:variables
}
